default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: intersol_development

test:
  <<: *default
  database: intersol_test

production:
  <<: *default
  database: intersol_production
  username: intersol
  password: <%= ENV['INTERSOL_DATABASE_PASSWORD'] %>
